### ISSUE TITLE
`join_stream` docs contradicting

### ISSUE THREAD

**Issue by d4h0** [vojtechkral/tokio-tasker#1]
Hi @vojtechkral,

Thanks for creating `tokio-tasker`, it looks very useful.

To me it seems, the documentation of `join_stream` is contradicting itself.

It says:

> Returns a Stream which yields join results as they become available, ie. as the tasks terminate.

And later:

> Note that just like with join() and try_join(), the stream will first wait until all Tasker clones are finished (via [finish()](https://docs.rs/tokio-tasker/latest/tokio_tasker/struct.Tasker.html#method.finish) or drop) **before yielding results**.

That sound like results are only returned by the stream after all `Tasker` instances are finished (which obviously wouldn't make sense).

From my testing it seems, that results are returned when they are available (as it should be).

I think, `before yielding results` should be rather something like `before it ends`.

Also, btw., on [crates.io](https://crates.io/crates/tokio-tasker) the link to the repo is missing (in the sidebar). There is a link to the 'examples' folder, however (which I missed...).

Thanks again, for creating `tokio-tasker`!

**Comment by vojtechkral** [comment]
> That sound like results are only returned by the stream after all `Tasker` instances are finished (which obviously wouldn't make sense).

That's exactly the case though. Well, all _other_ `Tasker` instances other than the one on which this is called. It has to be this way, when joining tasks, the `Tasker` needs to have all the join handles, otherwise another task could be added to the tasker as it is joining or after it has joined the tasks...

I guess in case of the join stream this could be relaxed somewhat in that the stream would start yielding right away and would stop after `Tasker` instances are finished and all tasks joined...

And of course the wording in doc could be improved too...

**Comment by d4h0** [comment]
> I guess in case of the join stream this could be relaxed somewhat in that the stream would start yielding right away and would stop after Tasker instances are finished and all tasks joined...

That is exactly what I was expecting. My thinking was, that the main reasons to use `join_stream` is, to get results (and to free up resources) as fast as possible. What happens if there is a really long-running `Tasker` instance that basically never finishes? If I remember correctly, the 'poll' method variants can be used to free up resources. I was thinking, `join_stream` works like that (but with a streaming interface).

**Comment by vojtechkral** [comment]
The whole `JoinStream` implementation is basically wrong, I'll have to redo it...

**Comment by vojtechkral** [comment]
@d4h0 I pushed refactored implementation in the `join-stream-refactor` branch, do you have a chance to test if that works better for you?

**Comment by d4h0** [comment]
@vojtechkral: I've tested the branch and everything seems to work as expected (the stream yields results immediately, and [failures of sub-tasks are caught](https://github.com/vojtechkral/tokio-tasker/issues/2)). 

Thank you 👍

**Comment by vojtechkral** [comment]
Cool, thanks for testing, I'll merge the commits & tag a release in a bit...
